#!/usr/bin/env bash
# UserPromptSubmit hook: refresh (TTL-throttled, offline-safe) and inject the
# work context — .claude/focus-story.md, generated by scripts/work-context.sh
# from the KyzoDB Work board. Context only; never blocks, never mutates.

set -euo pipefail

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || echo .)}"

# Consume stdin (the hook JSON) so the pipe never blocks; we don't need it.
cat >/dev/null 2>&1 || true

if [ -x "$root/scripts/work-context.sh" ]; then
  "$root/scripts/work-context.sh" >/dev/null 2>&1 || true
fi

f="$root/.claude/focus-story.md"
[ -s "$f" ] && cat "$f"
exit 0
